---
  - name: Generate firewall-address_list-{{inventory_hostname}}.rsc to check and add user
    template: src=address_list.rsc.j2 dest={{role_path}}/files/tmp/firewall-address_list-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Send firewall-address_list-{{inventory_hostname}}.rsc script
    command: scp -P {{ansible_port}} {{role_path}}/files/tmp/firewall-address_list-{{inventory_hostname}}.rsc {{ansible_user}}@{{ansible_host}}:/firewall-address_list-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Delete temporary firewall-address_list-{{inventory_hostname}}.rsc file
    file: path={{role_path}}/files/tmp/firewall-address_list-{{inventory_hostname}}.rsc state=absent
    delegate_to: localhost

  - name: Run firewall-address_list-{{inventory_hostname}}.rsc on router
    routeros_command:
      commands:  "/import firewall-address_list-{{inventory_hostname}}.rsc"
    tags: mikrotik_firewall_services
    register: firewall_address_list_out
    failed_when: firewall_interface_list_out['stdout_lines'][0][-1] is not search('Script file loaded and executed successfully')

  - name: Remove firewall-address_list-{{inventory_hostname}}.rsc from router
    routeros_command:
      commands:  "/file remove firewall-address_list-{{inventory_hostname}}.rsc"
    register: firewall_file_address_list_delete_out
    failed_when: firewall_file_address_list_delete_out['stdout_lines'][0][-1] is search('no such item')
    when: mikrotik_firewall.delete_configs_on_target_router
