---
  - name: Generate firewall-mangle-{{inventory_hostname}}.rsc to check and add user
    template: src=mangle.rsc.j2 dest={{role_path}}/files/tmp/firewall-mangle-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Send firewall-mangle-{{inventory_hostname}}.rsc script
    command: scp -P {{ansible_port}} {{role_path}}/files/tmp/firewall-mangle-{{inventory_hostname}}.rsc {{ansible_user}}@{{ansible_host}}:/firewall-mangle-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Delete temporary firewall-mangle-{{inventory_hostname}}.rsc file
    file: path={{role_path}}/files/tmp/firewall-mangle-{{inventory_hostname}}.rsc state=absent
    delegate_to: localhost

  - name: Run firewall-mangle-{{inventory_hostname}}.rsc on router
    routeros_command:
      commands:  "/import firewall-mangle-{{inventory_hostname}}.rsc"
    tags: mikrotik_firewall_services
    failed_when: firewall_interface_list_out['stdout_lines'][0][-1] is not search('Script file loaded and executed successfully')

  - name: Remove firewall-mangle-{{inventory_hostname}}.rsc from router
    routeros_command:
      commands:  "/file remove firewall-mangle-{{inventory_hostname}}.rsc"
    when: mikrotik_firewall.delete_configs_on_target_router
