---
  - name: Generate firewall-services-{{inventory_hostname}}.rsc to check and add user
    template: src=services.rsc.j2 dest={{role_path}}/files/tmp/firewall-services-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Send firewall-services-{{inventory_hostname}}.rsc script
    command: scp -P {{ansible_port}} {{role_path}}/files/tmp/firewall-services-{{inventory_hostname}}.rsc {{ansible_user}}@{{ansible_host}}:/firewall-services-{{inventory_hostname}}.rsc
    delegate_to: localhost

  - name: Delete temporary firewall-services-{{inventory_hostname}}.rsc file
    file: path={{role_path}}/files/tmp/firewall-services-{{inventory_hostname}}.rsc state=absent
    delegate_to: localhost

  - name: Run firewall-services-{{inventory_hostname}}.rsc on router
    routeros_command:
      commands: "/import firewall-services-{{inventory_hostname}}.rsc"

  - name: Remove firewall-services-{{inventory_hostname}}.rsc from router
    routeros_command:
      commands: "/file remove firewall-services-{{inventory_hostname}}.rsc"
    when: mikrotik_firewall.delete_configs_on_target_router
